#!/var/lang/bin/python3.8
# -*- coding: utf-8 -*-

from os import environ, execl
from shutil import which
from sys import argv, exit

environ['ORIG_HANDLER']=environ.get('_HANDLER')
environ['_HANDLER']='aws_observability.lambda_handler'
environ['OTEL_PYTHON_TRACER_PROVIDER']='sdk_tracer_provider'
environ['PYTHONPATH']='/opt/python:/var/runtime'

if __name__ == '__main__':
    executable = which(argv[1])
    exit(execl(executable, executable, *argv[2:]))
