AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws_observability_wrapper.handler
      Runtime: python3.7
      CodeUri: function/.
      Description: Test Python OTel Lambda
      MemorySize: 512
      Timeout: 15
      Environment:
        Variables:
          ORIG_HANDLER: lambda_function.lambda_handler
          INPROCESS_EXPORTER: false
      Policies:
        - AdministratorAccess
      Tracing: Active
      Layers:
        - !Ref libs
        - arn:aws:lambda:us-west-2:886273918189:layer:otel-py37:3
        - arn:aws:lambda:us-west-2:886273918189:layer:my-aoc-layer:2
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aws-observability-python2
      Description: Lambda OpenTelemetry Python demo.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
        - python3.7
        - python3.6
