version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "py37"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qcnbcfma33lw"
s3_prefix = "py37"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
