AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Lambda application that calls the Lambda API.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: function/.
      Description: Call the AWS Lambda API
      MemorySize: 512
      Timeout: 30
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: "/var/task/wrapper_script"
      Policies:
        - AdministratorAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: blank-python-lib
      Description: Lambda OpenTelemetry Python demo.
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
